export interface ICard {
    name?: string,
    price?: string,
    date?: string,
    dateToShot?: string,
    quantity?: number,
    avatar?: string,
    twitter?: string,
    discord?: string,
    borderPrice?: number,
    walletForMore?: string,
    walletForLess?: string,
    state?: string,
    SolForLess?: number,
    SolForMore?: number,
    judgePrice?: number,
    solForWhat?: string,
    judgeResult?: string,
    cardDescr?: string,
    cardDescrMore?: string,
    cardDescrLess?: string,
    currency?: string,
    eventDescr?: string,
    website?: string,
    result?:string,
    wallets?: {},
};