export interface ISendSolanaBtnProps {
    borderPrice?: number,
    descr?: string,
    wallet?: string,
    classN?: string,
    descr2?: number,
    judgePrice?: number, 
    name?: string,
    SolForWhat?: string,
    currency?: string,
    cardDescrMore?: string,
    cardDescrLess?: string,
    SolForMore?: number,
    SolForLess?: number,
}